source "https://rubygems.org"

gem "lita"
gem 'lita-slack'

gem 'lita-repeat', path: 'handlers/lita-repeat'
gem 'lita-aisatsu-police', path: 'handlers/lita-aisatsu-police'

# Uncomment to use the HipChat adapter
# gem "lita-hipchat"

# Uncomment to use the IRC adapter
# gem "lita-irc"

# Add handlers to give Lita new functionality.
# For example:
# gem "lita-google-images"
# gem "lita-karma"
